import sys; sys.path.insert(0,'.')
from engine.portfolio_bank import get_portfolio_model
m = get_portfolio_model('PM-JCNFUL-20260430-BE81')
dates = m.get('equity_dates_json', [])
hm    = m.get('monthly_heatmap_json', {})
ann   = m.get('annual_ret_json', [])
eq    = m.get('portfolio_equity_json', [])
print(f"Equity dates:  {len(dates)}  | eq values: {len(eq)}")
print(f"First 6 dates: {dates[:6]}")
print(f"Last 4 dates:  {dates[-4:]}")
print(f"Heatmap years ({len(hm)}): {sorted(hm.keys())}")
print(f"Annual rows: {len(ann)}")
print(f"Annual years: {[a['year'] for a in ann]}")
print()
print("Sample heatmap (first 3 years):")
for yr in sorted(hm.keys())[:3]:
    print(f"  {yr}: {sorted(hm[yr].keys())} => {list(hm[yr].values())[:3]}...")
print()
print(f"Final equity value: {eq[-1]:.4f} (CAGR check)")
